services:
  - type: web
    name: mindcare-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://jatavkhushi78_db_user:khushi12@cluster0.80yeens.mongodb.net/mindcare_counseling?retryWrites=true&w=majority&appName=Cluster0
      - key: CLIENT_URL
        sync: false
