const seedServices = [
  {
    title: "Individual Counseling",
    shortDescription: "One-on-one sessions for personal growth and emotional clarity.",
    description: "Personalized one-on-one therapy focused on helping you navigate personal challenges, emotional stress, life transitions, and self-discovery in a safe, confidential environment.",
    icon: "🧠",
    category: "Individual Therapy",
    duration: "50 mins",
    price: "₹1,200",
    benefits: [
      "Confidential and safe 1-on-1 space",
      "Tailored coping strategies for daily life",
      "Goal-oriented emotional support",
      "Build resilience and self-awareness",
    ],
    targetAudience: "Adults, Teens, Young Professionals",
    popular: true,
  },
  {
    title: "Relationship & Couples Therapy",
    shortDescription: "Strengthen communication and rebuild emotional intimacy.",
    description: "Supportive counseling for couples and partners to resolve conflicts, rebuild trust, foster healthier communication patterns, and deepen relational harmony.",
    icon: "💑",
    category: "Couples & Family",
    duration: "60 mins",
    price: "₹1,800",
    benefits: [
      "Constructive communication tools",
      "Conflict resolution without resentment",
      "Rebuilding trust and intimacy",
      "Pre-marital counseling guidance",
    ],
    targetAudience: "Couples, Married Partners, Pre-marital",
    popular: true,
  },
  {
    title: "Stress & Anxiety Management",
    shortDescription: "Overcome overwhelm, panic, and persistent worries.",
    description: "Evidence-based strategies using CBT and mindfulness to help you identify anxiety triggers, calm racing thoughts, regulate physical tension, and regain peace of mind.",
    icon: "🌿",
    category: "Mental Wellness",
    duration: "50 mins",
    price: "₹1,200",
    benefits: [
      "Cognitive Behavioral Therapy (CBT) techniques",
      "Mindfulness and breathing practices",
      "Panic and trigger response reduction",
      "Better sleep hygiene and relaxation",
    ],
    targetAudience: "Students, Working Professionals, Adults",
    popular: true,
  },
  {
    title: "Family Counseling",
    shortDescription: "Resolve family tensions and build a cohesive home dynamic.",
    description: "Helping family members understand each other's perspectives, heal unresolved grievances, set healthy boundaries, and establish positive family dynamics.",
    icon: "🏡",
    category: "Couples & Family",
    duration: "60 mins",
    price: "₹2,000",
    benefits: [
      "Parent-child communication bridges",
      "Intergenerational conflict resolution",
      "Healthy boundary setting",
      "Strengthened household bonds",
    ],
    targetAudience: "Parents, Teens, Extended Families",
    popular: false,
  },
  {
    title: "Career & Academic Guidance",
    shortDescription: "Navigate career burnout, transitions, and academic pressure.",
    description: "Clarify your professional and academic aspirations, overcome performance anxiety, prevent burnout, and design a purposeful, balanced career roadmap.",
    icon: "🎯",
    category: "Career & Growth",
    duration: "45 mins",
    price: "₹1,100",
    benefits: [
      "Overcoming imposter syndrome and burnout",
      "Clarifying strengths and career direction",
      "Time management and focus skills",
      "Navigating workplace or college stress",
    ],
    targetAudience: "Students, Job Seekers, Mid-Career Professionals",
    popular: false,
  },
  {
    title: "Depression & Grief Support",
    shortDescription: "Gentle guidance through low mood, loss, and bereavement.",
    description: "Compassionate, patient support to help you process profound loss, chronic feelings of sadness, numbness, and hopelessness, step by step.",
    icon: "🕯️",
    category: "Mental Wellness",
    duration: "50 mins",
    price: "₹1,400",
    benefits: [
      "Compassionate grief processing",
      "Re-engagement with daily routine",
      "Depression coping mechanisms",
      "Non-judgmental empathetic presence",
    ],
    targetAudience: "Adults dealing with loss or persistent low mood",
    popular: false,
  },
];

const seedCounselors = [
  {
    name: "Dr. Sarah Johnson",
    role: "Clinical Psychologist",
    specialization: "Anxiety, Depression & CBT",
    experience: "8+ years experience",
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80",
    bio: "Dr. Sarah is a licensed clinical psychologist specializing in Cognitive Behavioral Therapy (CBT) and mindfulness-based interventions for anxiety and depression.",
    languages: ["English", "Hindi"],
    fee: "₹1,500 / session",
    availableDays: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    education: "Ph.D. in Clinical Psychology, RCI Registered",
    email: "sarah.johnson@mindcare.com",
    phone: "+91 98234 56781",
  },
  {
    name: "Dr. Michael Lee",
    role: "Mental Health Counselor",
    specialization: "Stress Management & Work-Life Balance",
    experience: "6+ years experience",
    rating: 4.8,
    reviewsCount: 98,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=600&q=80",
    bio: "Dedicated to helping young professionals and students navigate burnout, life transitions, and chronic stress through actionable coping frameworks.",
    languages: ["English", "Hindi"],
    fee: "₹1,200 / session",
    availableDays: ["Tue", "Wed", "Thu", "Fri", "Sat"],
    education: "M.Sc. Counseling Psychology",
    email: "michael.lee@mindcare.com",
    phone: "+91 98234 56782",
  },
  {
    name: "Emily Williams",
    role: "Relationship Therapist",
    specialization: "Couples & Marriage Therapy",
    experience: "7+ years experience",
    rating: 4.9,
    reviewsCount: 115,
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=600&q=80",
    bio: "Certified emotionally-focused therapist working with couples to restore safety, open communication, and deep emotional resonance.",
    languages: ["English", "Hindi"],
    fee: "₹1,800 / session",
    availableDays: ["Mon", "Wed", "Thu", "Sat", "Sun"],
    education: "M.A. Family & Marriage Therapy",
    email: "emily.williams@mindcare.com",
    phone: "+91 98234 56783",
  },
  {
    name: "Dr. Rajesh Sharma",
    role: "Senior Consultant Psychiatrist & Counselor",
    specialization: "Mood Disorders & Neurodiversity",
    experience: "12+ years experience",
    rating: 5.0,
    reviewsCount: 210,
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=600&q=80",
    bio: "Brings extensive clinical expertise in diagnosing and supporting adult ADHD, depression, and severe anxiety with an empathetic, holistic approach.",
    languages: ["English", "Hindi"],
    fee: "₹2,000 / session",
    availableDays: ["Mon", "Tue", "Thu", "Fri"],
    education: "M.D. Psychiatry, RCI Registered",
    email: "rajesh.sharma@mindcare.com",
    phone: "+91 98234 56784",
  },
  {
    name: "Priya Mehta",
    role: "Child & Adolescent Psychologist",
    specialization: "Teens, Parenting & Academic Stress",
    experience: "5+ years experience",
    rating: 4.8,
    reviewsCount: 84,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
    bio: "Specializes in adolescent emotional challenges, exam stress, peer pressure, and helping parents establish supportive communication with their kids.",
    languages: ["English", "Hindi"],
    fee: "₹1,300 / session",
    availableDays: ["Mon", "Tue", "Wed", "Fri", "Sat"],
    education: "M.Sc. Child & Educational Psychology",
    email: "priya.mehta@mindcare.com",
    phone: "+91 98234 56785",
  },
];

module.exports = {
  seedServices,
  seedCounselors,
};
